import Link from 'next/link';
import { notFound } from 'next/navigation';
import Countdown from '../../../components/Countdown';
import { getHackathon } from '../../../lib/api/hackathons';
import { formatDate, formatPrize } from '../../../lib/formatters';

export const dynamic = 'force-dynamic';

export default async function HackathonDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let result;
  try { result = await getHackathon(id); } catch { notFound(); }
  const { hackathon, links, checks } = result;
  return <section className="detail-page"><Link className="back-link" href="/">← Back to opportunities</Link><div className="detail-header"><div><span className="eyebrow">{hackathon.source_name || hackathon.platform_name || 'Source pending'}</span><h1>{hackathon.title}</h1><p className="detail-organizer">{hackathon.organizer_name || 'Organizer not reported'}</p></div><span className="status-pill status-open">{hackathon.status}</span></div><div className="detail-layout"><div className="detail-main"><div className="countdown-panel"><span className="eyebrow">TIME REMAINING</span><Countdown deadline={hackathon.end_at_utc} /><span>Deadline · {formatDate(hackathon.end_at_utc)}</span></div><div className="detail-section"><span className="eyebrow">BEFORE YOU SIGN UP</span><p>{hackathon.what_to_know || 'Review the official rules, eligibility, judging criteria, prize terms, and submission requirements before signing up.'}</p></div><div className="detail-section"><span className="eyebrow">ABOUT THIS OPPORTUNITY</span><p>{hackathon.description || 'The source has not provided a longer description yet.'}</p></div><div className="detail-section"><span className="eyebrow">VERIFICATION NOTES</span><p>{hackathon.legitimacy_notes || 'Use the official source link below as the authority.'}</p></div></div><aside className="detail-aside"><div className="aside-panel"><span className="eyebrow">AT A GLANCE</span><dl><div><dt>Prize</dt><dd>{formatPrize(hackathon.prize_amount_minor, hackathon.prize_currency, hackathon.prize_text)}</dd></div><div><dt>Registration</dt><dd>{formatDate(hackathon.registration_deadline_utc)}</dd></div><div><dt>Participants</dt><dd>{hackathon.participant_count === null ? 'Not reported' : hackathon.participant_count.toLocaleString()}</dd></div><div><dt>Type</dt><dd>{hackathon.hackathon_type || 'Not reported'}</dd></div><div><dt>Location</dt><dd>{hackathon.online_or_location || hackathon.location_text || 'Not reported'}</dd></div></dl></div><a className="button button-primary full-width" href={hackathon.official_url} target="_blank" rel="noopener">Open official website ↗</a><div className="aside-panel trust-panel"><span className="trust-icon">✓</span><div><strong>{hackathon.verification_status}</strong><span>Source status for this listing</span></div></div></aside></div>{checks.length ? <div className="detail-section"><span className="eyebrow">VERIFICATION EVIDENCE</span><div className="source-links">{checks.map((check, index) => <div key={`${check.checked_at}-${index}`}><strong>{check.result}</strong> · {check.check_type} · {check.evidence_excerpt}</div>)}</div></div> : null}{links.length ? <div className="detail-section"><span className="eyebrow">SOURCE LINKS</span><div className="source-links">{links.map(link => <a key={link.url} href={link.url} target="_blank" rel="noopener">{link.label} ↗</a>)}</div></div> : null}</section>;
}
