<?php ob_start(); ?>
<section class="hero-section">
    <div class="hero-copy"><span class="eyebrow">THE SIGNAL BOARD</span><h1>Find the next<br><em>worthwhile</em> hackathon.</h1><p>Less noise. Better opportunities. A focused view of hackathons worth your time, with the details that matter before you commit.</p></div>
    <div class="hero-aside"><div class="orb orb-one"></div><div class="orb orb-two"></div><div class="hero-aside-content"><span class="eyebrow">DISCOVERY MODE</span><strong>Real sources.<br>Clear signals.</strong><span class="aside-note">Every listing will link back to its official source.</span></div></div>
</section>
<section class="summary-grid" aria-label="Dashboard summary"><div class="summary-card"><span class="summary-icon">◉</span><div><strong><?= number_format($summary['verified']) ?></strong><span>Verified active</span></div></div><div class="summary-card"><span class="summary-icon accent-icon">↘</span><div><strong><?= number_format($summary['ending']) ?></strong><span>Ending this week</span></div></div><div class="summary-card"><span class="summary-icon">◎</span><div><strong><?= number_format($summary['sources']) ?></strong><span>Source channels</span></div></div></section>
<section class="board-section"><div class="section-heading"><div><span class="eyebrow">LIVE BOARD</span><h2>Opportunities in view</h2></div><span class="result-count"><?= count($listings) ?> results</span></div>
<form class="filter-bar" method="get" action="/"><label class="search-field"><span>⌕</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Search by name, type, or organizer..."></label><select name="status" aria-label="Status"><option value="">All status</option><option value="active" <?= $filters['status'] === 'active' ? 'selected' : '' ?>>Active</option><option value="upcoming" <?= $filters['status'] === 'upcoming' ? 'selected' : '' ?>>Upcoming</option><option value="closed" <?= $filters['status'] === 'closed' ? 'selected' : '' ?>>Closed</option></select><select name="type" aria-label="Type"><option value="">All types</option><?php foreach ($options['types'] as $type): ?><option value="<?= e($type) ?>" <?= $filters['type'] === $type ? 'selected' : '' ?>><?= e($type) ?></option><?php endforeach; ?></select><select name="source" aria-label="Source"><option value="">All sources</option><?php foreach ($options['sources'] as $source): ?><option value="<?= e($source) ?>" <?= $filters['source'] === $source ? 'selected' : '' ?>><?= e($source) ?></option><?php endforeach; ?></select><select name="horizon" aria-label="Deadline horizon"><option value="">Any registration deadline</option><option value="1" <?= $filters['horizon'] === '1' ? 'selected' : '' ?>>Next 24 hours</option><option value="7" <?= $filters['horizon'] === '7' ? 'selected' : '' ?>>Next 7 days</option><option value="30" <?= $filters['horizon'] === '30' ? 'selected' : '' ?>>Next 30 days</option></select><select name="sort" aria-label="Sort"><option value="ending" <?= $filters['sort'] === 'ending' ? 'selected' : '' ?>>Ending soon</option><option value="noise" <?= $filters['sort'] === 'noise' ? 'selected' : '' ?>>Low-noise first</option><option value="prize" <?= $filters['sort'] === 'prize' ? 'selected' : '' ?>>Prize value</option><option value="newest" <?= $filters['sort'] === 'newest' ? 'selected' : '' ?>>Recently added</option></select><button class="button button-primary" type="submit">Filter</button></form>
<?php if (!$listings): ?><div class="empty-state"><div class="empty-icon">⌁</div><span class="eyebrow">NO VERIFIED LISTINGS YET</span><h3>The board is quiet for now.</h3><p>Hackathons will appear here once a real source has been connected and its official details have been checked. No invented opportunities, ever.</p><a class="text-link" href="/health">Check system status <span>↗</span></a></div><?php else: ?><div class="card-grid"><?php foreach ($listings as $item): require appRoot() . '/app/Views/components/hackathon-card.php'; endforeach; ?></div><?php endif; ?></section>
<?php $content = ob_get_clean(); require appRoot() . '/app/Views/layout.php'; ?>
